from .home import HomeView
from .year_goal.create_year_goal_views import CreateYearGoalView
from .year_goal.year_goal_detail_views import YearGoalDetailView
from .year_goal.year_goal_update_views import YearGoalUpdateView
from .year_goal.year_goal_achieve_views import YearGoalAchievementView
from .month_goal.month_goal_detail_views import MontGoalDetailView
from .month_goal.month_goal_update_views import MonthGoalUpdateView
from .month_goal.month_goal_achieve_views import MonthGoalAchieveView
from .todo.todo_create_views import TodoCreateView
from .todo.todo_detail_views import TodoDetailView
from .todo.todo_update_views import TodoUpdateView
from .todo.todo_achive_views import TodoAchieveView
from .todo.unachieved_todo_check_views import UnachievedTodoCheckView
from .feedback import FeedbackView
from .message.feedback_good import FeedbackGoodView
