# Generated by Django 5.1.5 on 2025-02-13 21:54

import django.db.models.deletion
import goal.models.year_goal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='メッセージ内容')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'お叱り'), (1, 'お褒め')], verbose_name='メッセージタイプ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'メッセージ',
                'verbose_name_plural': 'メッセージ一覧',
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='MonthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, '1月'), (2, '2月'), (3, '3月'), (4, '4月'), (5, '5月'), (6, '6月'), (7, '7月'), (8, '8月'), (9, '9月'), (10, '10月'), (11, '11月'), (12, '12月')], verbose_name='月')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='月の目標を入力してください')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未達'), (1, '達成')], default=0, verbose_name='達成状況')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '月目標',
                'verbose_name_plural': '月目標一覧',
                'db_table': 'month_goals',
            },
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='日々のタスクを入力してください')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未達'), (1, '達成')], default=0, verbose_name='達成状況')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('month_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal.monthgoal')),
            ],
            options={
                'verbose_name': 'TODO',
                'verbose_name_plural': 'TODO一覧',
                'db_table': 'todos',
            },
        ),
        migrations.CreateModel(
            name='YearGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(default=goal.models.year_goal.default_year_start, verbose_name='年目標')),
                ('title', models.CharField(max_length=50, verbose_name='年間目標を入力してください')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未達'), (1, '達成')], default=0, verbose_name='達成状況')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '年目標',
                'verbose_name_plural': '年目標一覧',
                'db_table': 'year_goals',
            },
        ),
        migrations.AddField(
            model_name='monthgoal',
            name='year_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal.yeargoal', verbose_name='年目標'),
        ),
        migrations.AlterUniqueTogether(
            name='monthgoal',
            unique_together={('year_goal', 'month')},
        ),
    ]
