# Generated by Django 5.1.5 on 2025-01-26 08:16

import django.db.models.deletion
import goal.models.year_goal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(default=goal.models.year_goal.default_year_start, verbose_name='年目標')),
                ('title', models.CharField(max_length=50, verbose_name='年間目標を入力してください')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未達'), (1, '達成')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'year_goals',
            },
        ),
    ]
