# Generated by Django 5.1.5 on 2025-02-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthgoal',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='月の目標を入力してください'),
        ),
    ]
