# Generated by Django 5.1.5 on 2025-01-26 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yeargoal',
            options={'verbose_name': '年目標', 'verbose_name_plural': '年目標一覧'},
        ),
        migrations.AlterField(
            model_name='yeargoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='yeargoal',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未達'), (1, '達成')], default=0, verbose_name='達成状況'),
        ),
        migrations.AlterField(
            model_name='yeargoal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='yeargoal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
