# Generated by Django 5.1.5 on 2025-01-26 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_alter_yeargoal_options_alter_yeargoal_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, '1月'), (2, '2月'), (3, '3月'), (4, '4月'), (5, '5月'), (6, '6月'), (7, '7月'), (8, '8月'), (9, '9月'), (10, '10月'), (11, '11月'), (12, '12月')], verbose_name='月')),
                ('title', models.CharField(max_length=50, verbose_name='月の目標を入力してください')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未達'), (1, '達成')], default=0, verbose_name='達成状況')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('year_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal.yeargoal', verbose_name='年目標')),
            ],
            options={
                'verbose_name': '月目標',
                'verbose_name_plural': '月目標一覧',
                'db_table': 'month_goals',
                'unique_together': {('year_goal', 'month')},
            },
        ),
    ]
