# Generated by Django 5.1.5 on 2025-01-26 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0003_monthgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='日々のタスクを入力してください')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未達'), (1, '達成')], default=0, verbose_name='達成状況')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('month_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal.monthgoal')),
            ],
            options={
                'verbose_name': 'TODO',
                'verbose_name_plural': 'TODO一覧',
                'db_table': 'todos',
            },
        ),
    ]
