# Generated by Django 5.1.5 on 2025-01-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0004_todos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='メッセージ内容')),
                ('message_type', models.PositiveSmallIntegerField(choices=[(0, 'お叱り'), (1, 'お褒め')], verbose_name='メッセージタイプ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'メッセージ',
                'verbose_name_plural': 'メッセージ一覧',
                'db_table': 'messages',
            },
        ),
    ]
