# Generated by Django 5.1.5 on 2025-01-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birthday',
            field=models.DateField(null=True, verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='users',
            name='dethday',
            field=models.DateField(null=True, verbose_name='想定寿命'),
        ),
    ]
