# Generated by Django 5.1.5 on 2025-01-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0002_todomodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoModel',
        ),
    ]
